[package]
name = "rush"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exec = "0.3.1"
gethostname = "0.4.1"
libc = "0.2.139"
nix = "0.26.1"
shell-words = "1.1.0"
signal-hook = "0.3.14"
